version: '1'

services:
  microservicio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:oracle:thin:@bwghafsizhtlg4hy_high?TNS_ADMIN=/app/oracle_wallet/
      - SPRING_DATASOURCE_USERNAME=ADMIN
      - SPRING_DATASOURCE_PASSWORD=Felipe_130886
    restart: always